access the environment input using github.event.inputs.environment

diff --git a/.github/actions/set-environment-variables/action.yml b/.github/actions/set-environment-variables/action.yml
--- a/.github/actions/set-environment-variables/action.yml
+++ b/.github/actions/set-environment-variables/action.yml
@@ -15,11 +15,11 @@ runs:
         API_CHALLENGES_LIVE: ${{ github.secrets.API_CHALLENGES_LIVE }}
         API_CHALLENGES_TEST: ${{ github.secrets.API_CHALLENGES_TEST }}
       run: |
-        if [ "${{inputs.environment}}" == "live" ]; then
+        if [ "${{ github.event.inputs.environment }}" == "live" ]; then
           echo "API_BASE_URL=${API_CHALLENGES_LIVE}" >> $GITHUB_ENV
-        elif [ "${{inputs.environment}}" == "test" ]; then
+        elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
           echo "API_BASE_URL=${API_CHALLENGES_TEST}" >> $GITHUB_ENV
         else
-          echo "Error: Unknown environment '${{inputs.environment}}'. Please use 'live' or 'test'." >&2
+          echo "Error: Unknown environment '${{ github.eventinputs.environment }}'. Please use 'live' or 'test'." >&2
           exit 1
         fi
