changed with to args

diff --git a/.github/actions/set-environment-variables/action.yml b/.github/actions/set-environment-variables/action.yml
--- a/.github/actions/set-environment-variables/action.yml
+++ b/.github/actions/set-environment-variables/action.yml
@@ -14,14 +14,14 @@ runs:
       env:
         API_CHALLENGES_LIVE: ${{ github.secrets.API_CHALLENGES_LIVE }}
         API_CHALLENGES_TEST: ${{ github.secrets.API_CHALLENGES_TEST }}
-      with:
-        environment: ${{ github.event.inputs.environment }}
+      args:
+        - ${{ inputs.environment }}
       run: |
-        if [ "${1}" == "live" ]; then
+        if [ "${0}" == "live" ]; then
           echo "API_BASE_URL=${API_CHALLENGES_LIVE}" >> $GITHUB_ENV
-        elif [ "${1}" == "test" ]; then
+        elif [ "${0}" == "test" ]; then
           echo "API_BASE_URL=${API_CHALLENGES_TEST}" >> $GITHUB_ENV
         else
-          echo "Error: Unknown environment '${1}'. Please use 'live' or 'test'." >&2
+          echo "Error: Unknown environment '${0}'. Please use 'live' or 'test'." >&2
           exit 1
         fi
