environment input as an argument to the script using the with keyword

diff --git a/.github/actions/set-environment-variables/action.yml b/.github/actions/set-environment-variables/action.yml
--- a/.github/actions/set-environment-variables/action.yml
+++ b/.github/actions/set-environment-variables/action.yml
@@ -14,13 +14,14 @@ runs:
       env:
         API_CHALLENGES_LIVE: ${{ github.secrets.API_CHALLENGES_LIVE }}
         API_CHALLENGES_TEST: ${{ github.secrets.API_CHALLENGES_TEST }}
+      with:
+        environment: ${{ github.event.inputs.environment }}
       run: |
-        echo "github.event.inputs.environment: ${github.event.inputs.environment}"
-        if [ "${{ github.event.inputs.environment }}" == "live" ]; then
+        if [ "${1}" == "live" ]; then
           echo "API_BASE_URL=${API_CHALLENGES_LIVE}" >> $GITHUB_ENV
-        elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
+        elif [ "${1}" == "test" ]; then
           echo "API_BASE_URL=${API_CHALLENGES_TEST}" >> $GITHUB_ENV
         else
-          echo "Error: Unknown environment '${{ github.event.inputs.environment }}'. Please use 'live' or 'test'." >&2
+          echo "Error: Unknown environment '${1}'. Please use 'live' or 'test'." >&2
           exit 1
         fi
