fixed the variable name issue

diff --git a/.github/actions/set-environment-variables/action.yml b/.github/actions/set-environment-variables/action.yml
--- a/.github/actions/set-environment-variables/action.yml
+++ b/.github/actions/set-environment-variables/action.yml
@@ -12,11 +12,11 @@ runs:
     - name: Set BASE_URL
       shell: bash
       run: |
-        if [ "${{ inputs.environment }}" == "live" ]; then
-          echo "API_BASE_URL=${{ vars.API_CHALLENGES_LIVE }}" >> $GITHUB_ENV
-        elif [ "${{ inputs.environment }}" == "test" ]; then
-          echo "API_BASE_URL=${{ vars.API_CHALLENGES_TEST }}" >> $GITHUB_ENV
+        if [ "${{inputs.environment}}" == "live" ]; then
+          echo "API_BASE_URL=${{vars.API_CHALLENGES_LIVE}}" >> $GITHUB_ENV
+        elif [ "${{inputs.environment}}" == "test" ]; then
+          echo "API_BASE_URL=${{vars.API_CHALLENGES_TEST}}" >> $GITHUB_ENV
         else
-          echo "Error: Unknown environment '${{ inputs.environment }}'. Please use 'live' or 'test'." >&2
+          echo "Error: Unknown environment '${{inputs.environment}}'. Please use 'live' or 'test'." >&2
           exit 1
         fi
